# Generated by Django 4.0.2 on 2022-02-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useracc', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('clothing', 'clothing'), ('electronics', 'electronics'), ('footwear', 'footwear')], max_length=50),
        ),
    ]
